# Generated by Django 4.0.4 on 2022-04-19 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_gone', to='location.location')),
                ('starting_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_to_go', to='location.location')),
            ],
        ),
    ]
