# Generated by Django 4.0.4 on 2022-04-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_google_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='distance',
            new_name='miles',
        ),
        migrations.AddField(
            model_name='distance',
            name='kilometers',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
